[debug]
address = "127.0.0.1"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8080
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "critical"

[global.databases]
main_db = { url = "postgres://api-renov:api_pswd@localhost/debug" }